### ISSUE TITLE
Matrix dimensions do not match

### ISSUE THREAD

**Issue by yenerunver** [atcemgil/notes#2]
In `notes/MultiLayerPerceptron.ipynb`, there is a dimensional conflict in this function:

<pre>
def mlp_fun(x, Weight, Bias, Func):
    f = Variable(x, requires_grad=False)
    NumOfLayers = len(Weight)
    for i in range(NumOfLayers):
        f = Func[i](torch.matmul(Weight[i], f) + Bias[i])
    return f
</pre>

I have printed all steps for a 1,2,1 sized network, below are the results:
![image](https://user-images.githubusercontent.com/8215944/48833671-f23ba680-ed8c-11e8-88f4-79630c7ad0c5.png)

While the result of `torch.matmul(Weight[0], x)` is a **1x2** matrix, `Bias[0]` is a **2x1** vector and their summation is a **2x2** matrix.

This leads to a dimensional conflict in `f` results.

**Comment by yenerunver** [comment]
`sizes=[4,2,1]` example:

![image](https://user-images.githubusercontent.com/8215944/48834454-eb159800-ed8e-11e8-9d1a-372e3644cf2a.png)

**Comment by alper111** [comment]
I guess if you feed `x` as a `feature_size x batch_size` vector, then there should be no problem. For example, if you want to feed an input with 4-dimensional feature space, then x should be of size (4, 1). You can easily do this by feeding `x.view(feature_size, -1)`. This will assure that your input is of size (feature_size, batch_size).

**Comment by yenerunver** [comment]
A detailed version of `sizes=[4,2,1]`:

![image](https://user-images.githubusercontent.com/8215944/48837404-54e57000-ed96-11e8-8a27-d7098d34a050.png)

**Comment by yenerunver** [comment]
I think I have found the problem. I was creating inputs as `torch.rand(sizes[0])`, instead of `torch.rand(sizes[0], 1)`. Second one solves the conflicts.
